# Generated by Django 4.2.5 on 2024-03-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_watchlist_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='in_watchlist',
            field=models.BooleanField(default=True),
        ),
    ]
