# Generated by Django 4.2.5 on 2024-03-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listing_in_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='in_watchlist',
            field=models.BooleanField(default=False),
        ),
    ]
