# Generated by Django 4.2.5 on 2024-03-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_bid_listing_alter_listing_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='is_watchlisted',
            field=models.BooleanField(default=False),
        ),
    ]
