# Generated by Django 4.2.5 on 2024-03-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_watchlist_is_watchlisted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='is_watchlisted',
            field=models.BooleanField(default=True),
        ),
    ]
