# Generated by Django 4.2.5 on 2024-03-22 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_watchlist_is_watchlisted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='is_watchlisted',
        ),
    ]
