# Generated by Django 4.2.5 on 2024-03-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_remove_watchlist_is_watchlisted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.CharField(default=0, max_length=600),
        ),
    ]
